## Data Cleaning
#### In this notebook we are loading the data from both pro football reference and fantasydata.com. Then we standardize formatting across the data sets, merge the data together, and finally create some metrics to provide us with further insights into these players

#### Importing Packages

In [1]:
import pandas as pd
import numpy as np

#### Loading General Fantasy Stats:
##### This is the data from pro-football-reference.com including PPR fantasy points, passing yards, rushing yards, etc... They include a rank column, but since we are making our own rankings we can remove that column

In [2]:
Fantasy_FB_Data_Raw25 = pd.read_csv('../Fantasyfb_Data/Fantasy FB Data 2025.csv')
Fantasy_FB_Data_Raw24 = pd.read_csv('../Fantasyfb_Data/Fantasy FB Data 2024.csv')
Fantasy_FB_Data_Raw23 = pd.read_csv('../Fantasyfb_Data/Fantasy FB Data 2023.csv')
Fantasy_FB_Data_Raw22 = pd.read_csv('../Fantasyfb_Data/Fantasy FB Data 2022.csv')
Fantasy_FB_Data_Raw21 = pd.read_csv('../Fantasyfb_Data/Fantasy FB Data 2021.csv')
Fantasy_FB_Data_Raw20 = pd.read_csv('../Fantasyfb_Data/Fantasy FB Data 2020.csv')
Fantasy_FB_Data_Raw19 = pd.read_csv('../Fantasyfb_Data/Fantasy FB Data 2019.csv')
Fantasy_FB_Data_Raw18 = pd.read_csv('../Fantasyfb_Data/Fantasy FB Data 2018.csv')
Fantasy_FB_Data_Raw17 = pd.read_csv('../Fantasyfb_Data/Fantasy FB Data 2017.csv')
FFBD2025 = Fantasy_FB_Data_Raw25.drop('Rk', axis=1)
FFBD2025.set_index('Player', inplace=True)
FFBD2024 = Fantasy_FB_Data_Raw24.drop('Rk', axis=1)
FFBD2024.set_index('Player', inplace=True)
FFBD2023 = Fantasy_FB_Data_Raw23.drop('Rk', axis=1)
FFBD2023.set_index('Player', inplace=True)
FFBD2022 = Fantasy_FB_Data_Raw22.drop('Rk', axis=1)
FFBD2022.set_index('Player', inplace=True)
FFBD2021 = Fantasy_FB_Data_Raw21.drop('Rk', axis=1)
FFBD2021.set_index('Player', inplace=True)
FFBD2020 = Fantasy_FB_Data_Raw20.drop('Rk', axis=1)
FFBD2020.set_index('Player', inplace=True)
FFBD2019 = Fantasy_FB_Data_Raw19.drop('Rk', axis=1)
FFBD2019.set_index('Player', inplace=True)
FFBD2018 = Fantasy_FB_Data_Raw18.drop('Rk', axis=1)
FFBD2018.set_index('Player', inplace=True)
FFBD2017 = Fantasy_FB_Data_Raw17.drop('Rk', axis=1)
FFBD2017.set_index('Player', inplace=True)

#### Loading Snap Count Data
##### This is the data from fantasydata.com/nfl which includes snap counts unlike the pro football reference files. We'll need to rename some columns and adjust some player names so that we can merge the data after importing.

In [3]:
Fantasy_FB_Data_RawSnap25 = pd.read_csv('../Fantasyfb_Data/FFBD2025_SNAPS.csv')
Fantasy_FB_Data_RawSnap24 = pd.read_csv('../Fantasyfb_Data/FFBD2024_SNAPS.csv')
Fantasy_FB_Data_RawSnap23 = pd.read_csv('../Fantasyfb_Data/FFBD2023_SNAPS.csv')
Fantasy_FB_Data_RawSnap22 = pd.read_csv('../Fantasyfb_Data/FFBD2022_SNAPS.csv')
Fantasy_FB_Data_RawSnap21 = pd.read_csv('../Fantasyfb_Data/FFBD2021_SNAPS.csv')
Fantasy_FB_Data_RawSnap20 = pd.read_csv('../Fantasyfb_Data/FFBD2020_SNAPS.csv')
Fantasy_FB_Data_RawSnap19 = pd.read_csv('../Fantasyfb_Data/FFBD2019_SNAPS.csv')
Fantasy_FB_Data_RawSnap18 = pd.read_csv('../Fantasyfb_Data/FFBD2018_SNAPS.csv')
Fantasy_FB_Data_RawSnap17 = pd.read_csv('../Fantasyfb_Data/FFBD2017_SNAPS.csv')
Weeks_18 = ['Week 1','Week 2','Week 3','Week 4','Week 5','Week 6','Week 7','Week 8','Week 9','Week 10','Week 11','Week 12','Week 13','Week 14','Week 15','Week 16','Week 17', 'Week 18']
Weeks_17 = ['Week 1','Week 2','Week 3','Week 4','Week 5','Week 6','Week 7','Week 8','Week 9','Week 10','Week 11','Week 12','Week 13','Week 14','Week 15','Week 16','Week 17']
FFBD2025snp = Fantasy_FB_Data_RawSnap25
FFBD2024snp = Fantasy_FB_Data_RawSnap24.drop(columns=Weeks_18)
FFBD2023snp = Fantasy_FB_Data_RawSnap23.drop(columns=Weeks_18)
FFBD2022snp = Fantasy_FB_Data_RawSnap22.drop(columns=Weeks_18)
FFBD2021snp = Fantasy_FB_Data_RawSnap21.drop(columns=Weeks_18)
FFBD2020snp = Fantasy_FB_Data_RawSnap20.drop(columns=Weeks_17)
FFBD2019snp = Fantasy_FB_Data_RawSnap19.drop(columns=Weeks_17)
FFBD2018snp = Fantasy_FB_Data_RawSnap18.drop(columns=Weeks_17)
FFBD2017snp = Fantasy_FB_Data_RawSnap17.drop(columns=Weeks_17)

#### Standardize column names

In [4]:
FFBD2025.rename(columns = {'Tgt (Rec)' : 'Tgt'}, inplace = True)
FFBD2025.rename(columns = {'Y/A (Rush)' : 'Y/A'}, inplace = True)
FFBD2025.rename(columns = {'Receptions' : 'Rec'}, inplace = True)
FFBD2024.rename(columns = {'Tgt (Rec)' : 'Tgt'}, inplace = True)
FFBD2024.rename(columns = {'Y/A (Rush)' : 'Y/A'}, inplace = True)
FFBD2024.rename(columns = {'Receptions' : 'Rec'}, inplace = True)
FFBD2021.rename(columns = {'Att. (Pass)' : 'Att (Pass)'}, inplace = True)
FFBD2017.rename(columns = {'Yds  (Rush)' : 'Yds (Rush)'}, inplace = True)
FFBD2017.rename(columns = {'TD  (Rush)' : 'TD (Rush)'}, inplace = True)
FFBD2025snp.rename(columns = {'TTL' : 'Total Snaps','AVG' : 'Avg Snaps'}, inplace = True)
#Standardizes column names in snap count data for merging with other data
Rename_dict = {
    'NAME' : 'Player',
    'Avg' : 'Avg Snaps',
    'Total' : 'Total Snaps'
}
def rename_columns(df, rename_map):
    df.rename(columns=rename_map, inplace=True)

# Creates lists so that we can apply functions to each subset of data rather than doing it individually
Basedfs = [FFBD2025,FFBD2024,FFBD2023,FFBD2022,FFBD2021,FFBD2020,FFBD2019,FFBD2018,FFBD2017]
dfs = [FFBD2024snp, FFBD2023snp, FFBD2022snp, FFBD2021snp, FFBD2020snp, FFBD2019snp, FFBD2018snp, FFBD2017snp]
for df in dfs:
    rename_columns(df, Rename_dict)

#Set the index in snap count data equal to 'Player' column
for df in dfs:
    df.set_index('Player', inplace=True)

#### Creating a function to clean up and standardize the pro football reference data
##### There were a few discrepancies that needed adjusting between the two data sources. In the following function we fix the player name column so that sufixes as well as player initials are standardized. We are also removing the fullback position and filling the na values in the two point try columns with 0.0

In [5]:
def clean_FFBD(df):
    df = df[~(df[['Cmp', 'Att (Pass)', 'Tgt']].isna().all(axis=1))]
    df = df.drop_duplicates()
    df[['2PM', '2PP']] = df[['2PM', '2PP']].fillna(0.0)
    df.index = df.index.str.rstrip('*+')
    df.index = df.index.str.replace(r'\sJr\.$', '', regex = True)
    df.index = df.index.str.replace(r'\sSr\.$', '', regex = True) 
    df.index = df.index.str.replace(r'\.', '', regex = True)
    df.index = df.index.str.replace(r'\sIII$', '', regex = True)
    df.index = df.index.str.replace(r'\sII$', '', regex = True)
    df.index = df.index.str.replace(r'\sIV$', '', regex = True)
    df.index = df.index.str.replace(r'\sV$', '', regex = True)
    df.index = df.index.str.upper().str.strip()
    df = df[df['FantPos'] != 'FB']
    return df

FFBD2025 = clean_FFBD(FFBD2025)
FFBD2024 = clean_FFBD(FFBD2024)
FFBD2023 = clean_FFBD(FFBD2023)
FFBD2022 = clean_FFBD(FFBD2022)
FFBD2021 = clean_FFBD(FFBD2021)
FFBD2020 = clean_FFBD(FFBD2020)
FFBD2019 = clean_FFBD(FFBD2019)
FFBD2018 = clean_FFBD(FFBD2018)
FFBD2017 = clean_FFBD(FFBD2017)

#### Removing naN for 'PPR' column
##### If your fantasy league uses a different scoring method, there are a few others in the data that can be used. Since my leagues are Full PPR, I'll drop any players with na values in the PPR column. Most of these players are not fantasy relevant, so we're not losing any valuable player data.

In [6]:
def remove_PPRna(df):
    df = df[~(df['PPR'].isna())]
    return df
FFBD2025 = remove_PPRna(FFBD2025)
FFBD2024 = remove_PPRna(FFBD2024)
FFBD2023 = remove_PPRna(FFBD2023)
FFBD2022 = remove_PPRna(FFBD2022)
FFBD2021 = remove_PPRna(FFBD2021)
FFBD2020 = remove_PPRna(FFBD2020)
FFBD2019 = remove_PPRna(FFBD2019)
FFBD2018 = remove_PPRna(FFBD2018)
FFBD2017 = remove_PPRna(FFBD2017)

#### Creating a function to clean up and standardize the data from fantasydata.com
##### Here we make a similar function to the one for the pro football reference data: making sure that suffixes, initials and roman numerals are fixed between every data frame

In [7]:
FFBD2025snp.set_index('Player',inplace=True)
FFBD2025snp.index.astype('str')

Index(['Caleb Williams', 'Bo Nix', 'Dak Prescott', 'Matthew Stafford',
       'Trevor Lawrence', 'Baker Mayfield', 'Jared Goff', 'Drake Maye',
       'Justin Herbert', 'Josh Allen',
       ...
       'Adrian Martinez', 'Trey Sermon', 'Sione Vaki', 'Kaden Davis',
       'Malik Cunningham', 'Coleman Owen', 'Lawrence Cager',
       'Maurice Alexander', 'Chase Edmonds', 'Jimmy Holiday'],
      dtype='object', name='Player', length=625)

In [8]:
dfs = [FFBD2025snp, FFBD2024snp, FFBD2023snp, FFBD2022snp, FFBD2021snp, FFBD2020snp, FFBD2019snp, FFBD2018snp, FFBD2017snp]
for df in dfs:
    df.index = df.index.str.replace(r'\sJr\.$', '', regex = True)
    df.index = df.index.str.replace(r'\sSr\.$', '', regex = True) 
    df.index = df.index.str.replace(r'\.', '', regex = True)
    df.index = df.index.str.replace(r'\sIII$', '', regex = True)
    df.index = df.index.str.replace(r'\sII$', '', regex = True)
    df.index = df.index.str.replace(r'\sIV$', '', regex = True)
    df.index = df.index.str.replace(r'\sV$', '', regex = True)
    df.index = df.index.str.upper().str.strip()

#### Labeling the year
##### This will attatch the year to the player name so that we can merge and format all of the individual years of data as panel data

In [9]:
FFBD2025.index = FFBD2025.index + '_2025'
FFBD2024.index = FFBD2024.index + '_2024'
FFBD2023.index = FFBD2023.index + '_2023'
FFBD2022.index = FFBD2022.index + '_2022'
FFBD2021.index = FFBD2021.index + '_2021'
FFBD2020.index = FFBD2020.index + '_2020'
FFBD2019.index = FFBD2019.index + '_2019'
FFBD2018.index = FFBD2018.index + '_2018'
FFBD2017.index = FFBD2017.index + '_2017'

FFBD2025snp.index = FFBD2025snp.index + '_2025'
FFBD2024snp.index = FFBD2024snp.index + '_2024'
FFBD2023snp.index = FFBD2023snp.index + '_2023'
FFBD2022snp.index = FFBD2022snp.index + '_2022'
FFBD2021snp.index = FFBD2021snp.index + '_2021'
FFBD2020snp.index = FFBD2020snp.index + '_2020'
FFBD2019snp.index = FFBD2019snp.index + '_2019'
FFBD2018snp.index = FFBD2018snp.index + '_2018'
FFBD2017snp.index = FFBD2017snp.index + '_2017'

#### Merging the data
##### First we can merge the data to form panel data, then drop some unnecessary or duplicate columns

In [10]:
FFBD_Merged = pd.concat([FFBD2025, FFBD2024, FFBD2023, FFBD2022, FFBD2021, FFBD2020, FFBD2019, FFBD2018, FFBD2017])

In [11]:
FFBDsnp_Merged = pd.concat(dfs)

#### Examining the two data frames

In [12]:
FFBD_Merged

,Tm,FantPos,Age,G,GS,Cmp,Att (Pass),Yds (Pass),TD (Pass),Int,...,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank,-9999
Player,,,,,,,,,,,,,,,,,,,,,
JONATHAN TAYLOR_2025,IND,RB,26.0,17.0,17.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,316.0,362.3,369.3,339.3,158.0,1.0,1.0,TaylJo02
CHRISTIAN MCCAFFREY_2025,SFO,RB,29.0,17.0,17.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,315.0,416.6,422.6,365.6,157.0,2.0,2.0,McCaCh01
BIJAN ROBINSON_2025,ATL,RB,23.0,17.0,17.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,292.0,370.8,379.8,331.3,135.0,3.0,3.0,RobiBi01
JAHMYR GIBBS_2025,DET,RB,23.0,17.0,17.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,290.0,366.9,373.9,328.4,133.0,4.0,4.0,GibbJa01
PUKA NACUA_2025,LAR,WR,24.0,16.0,15.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,246.0,375.0,382.0,310.5,121.0,1.0,5.0,NacuPu00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
JOHN ROSS_2017,CIN,WR,22.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.0,-0.8,0.2,-0.8,NaN,226.0,NaN,NaN
JAKE RUDOCK_2017,DET,QB,24.0,3.0,0.0,3.0,5.0,24.0,0.0,1.0,...,0.0,0.0,-1.0,-1.0,NaN,NaN,NaN,72.0,NaN,NaN
TYLER BRAY_2017,KAN,QB,26.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,-2.0,-2.0,-1.0,-2.0,NaN,74.0,NaN,NaN
TEDDY BRIDGEWATER_2017,MIN,QB,25.0,1.0,0.0,0.0,2.0,0.0,0.0,1.0,...,0.0,0.0,-2.0,-2.3,-1.3,-1.3,NaN,75.0,NaN,NaN
DEVANTE MAYS_2017,GNB,RB,23.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-2.0,1.1,2.1,-0.4,NaN,171.0,NaN,NaN

In [13]:
FFBDsnp_Merged

                       Total Snaps  Avg Snaps  POS TEAM  DEPTH  TM SNAP %   TD
Player
CALEB WILLIAMS_2025           1143       67.2  NaN  NaN    NaN        NaN  NaN
BO NIX_2025                   1136       66.8  NaN  NaN    NaN        NaN  NaN
DAK PRESCOTT_2025             1135       66.8  NaN  NaN    NaN        NaN  NaN
MATTHEW STAFFORD_2025         1117       65.7  NaN  NaN    NaN        NaN  NaN
TREVOR LAWRENCE_2025          1114       65.5  NaN  NaN    NaN        NaN  NaN
...                            ...        ...  ...  ...    ...        ...  ...
VICTOR BOLDEN_2017              28        3.0   WR   SF    NaN        2.5    0
VINCE MAYLE_2017                21        1.0   WR  BAL    NaN        1.9    0
WILL TYE_2017                  101       33.0   TE  NYJ    NaN        9.7    0
ZACH MILLER_2017               314       39.0   TE  CHI    NaN       31.7    2
ZACH ZENNER_2017                65        8.0   RB  DET    NaN        6.2    }

[5559 rows x 7 columns]

In [14]:
FFBD_Merged.drop(columns = ['OvRank', 'PosRank', 'VBD', 'FDPt', 'DKPt', 'FantPt'], inplace=True)
FFBDsnp_Merged.drop(columns = ['POS','TEAM', 'DEPTH', 'TD'], inplace=True)

##### Before merging the two panel data from pro-football reference and fantasydata.com together, there are a few fantasy relevant players that did not get standardized by our functions which I've decided to fix with the below:

In [15]:
FFBDsnp_Merged.index = FFBDsnp_Merged.index.str.replace(r'CHIG OKONKWO','CHIGOZIEM OKONKWO')
FFBDsnp_Merged.index = FFBDsnp_Merged.index.str.replace(r'DEE ESKRIDGE','D\'WAYNE ESKRIDGE')
FFBDsnp_Merged.index = FFBDsnp_Merged.index.str.replace(r'GABE DAVIS','GABRIEL DAVIS')
FFBDsnp_Merged.index = FFBDsnp_Merged.index.str.replace(r'JOSHUA PALMER','JOSH PALMER')
FFBDsnp_Merged.index = FFBDsnp_Merged.index.str.replace(r'MITCH TRUBISKY','MITCHELL TRUBISKY')
FFBDsnp_Merged.index = FFBDsnp_Merged.index.str.replace(r'SCOTTY MILLER','SCOTT MILLER')

#### Merging the two panel data together to create one larger data set

In [16]:
FFBD_tot = pd.merge(FFBD_Merged, FFBDsnp_Merged, left_index=True, right_index=True, how = 'inner')

#### Creating columns to provide further insights
##### Sometimes it can be interesting not just to view a player's usual statistics – yards,receptions,etc... – but to look at how many fantasy points they score each target, snap, catch, etc...

In [17]:

# Passing
mask = (FFBD_tot['Att (Pass)'] !=0) & (pd.notna(FFBD_tot['Att (Pass)']))
FFBD_tot['PPR (Pass)'] = (FFBD_tot['TD (Pass)'] * 4) + (FFBD_tot['Yds (Pass)'] * 0.04) + (FFBD_tot['Int']* -2)
FFBD_tot.loc[mask, 'PPR_PassAtt'] = FFBD_tot.loc[mask, 'PPR (Pass)'] / FFBD_tot.loc[mask, 'Att (Pass)']
FFBD_tot.loc[mask, 'Y/A (Pass)'] = FFBD_tot.loc[mask, 'Yds (Pass)'] / FFBD_tot.loc[mask, 'Att (Pass)']


# Rushing
mask = (FFBD_tot['Att (Rush)'] !=0) & (pd.notna(FFBD_tot['Att (Rush)']))
FFBD_tot['PPR (Rush)'] = (FFBD_tot['TD (Rush)'] * 6) + (FFBD_tot['Yds (Rush)'] * 0.1)
FFBD_tot.loc[mask, 'PPR_RushAtt'] = FFBD_tot.loc[mask, 'PPR (Rush)'] / FFBD_tot.loc[mask, 'Att (Rush)']

# Receiving
FFBD_tot['PPR (Rec)'] = FFBD_tot['Rec'] + (FFBD_tot['Yds (Rec)'] * 0.1) + (FFBD_tot['TD (Rec)'] * 6)
mask = (FFBD_tot['Tgt'] !=0) & (pd.notna(FFBD_tot['Tgt']))
FFBD_tot.loc[mask, 'PPR_Tgt'] = FFBD_tot.loc[mask, 'PPR (Rec)'] / FFBD_tot.loc[mask, 'Tgt']
FFBD_tot.loc[mask, 'Tgt_gm'] = FFBD_tot.loc[mask, 'Tgt'] / FFBD_tot.loc[mask, 'G']

mask = (FFBD_tot['Rec'] !=0) & (pd.notna(FFBD_tot['Rec']))
FFBD_tot.loc[mask, 'PPR_Rec'] = FFBD_tot.loc[mask, 'PPR (Rec)'] / FFBD_tot.loc[mask, 'Rec']

# Snap Count
mask = (FFBD_tot['Total Snaps'] !=0) & (pd.notna(FFBD_tot['Total Snaps']))
FFBD_tot.loc[mask, 'PPR_Snap'] = FFBD_tot.loc[mask, 'PPR'] / FFBD_tot.loc[mask, 'Total Snaps']

#### Creating Passer Rating Column
##### One insight that can tell us a lot about a quarterback's overall performance is passer rating. The formula for passer rating is as follows:
##### (5(Passing Yards/Pass Attempts - 3) + 0.25(Completions/Pass Attempts - 0.3) + 20(Pass TD/Pass Attempts) + (2.375 - 25(Interceptions/Pass Attempts)))/6 * 100

In [18]:
mask = (FFBD_tot['Att (Pass)'] !=0) & (pd.notna(FFBD_tot['Att (Pass)']))

FFBD_tot.loc[mask, 'Y/A_rate'] = ((FFBD_tot.loc[mask, 'Yds (Pass)'] / FFBD_tot.loc[mask, 'Att (Pass)']) - 3) * 5
FFBD_tot.loc[mask, 'Cmp_rate'] = ((FFBD_tot.loc[mask, 'Cmp'] / FFBD_tot.loc[mask, 'Att (Pass)']) - 0.3) * 0.25
FFBD_tot.loc[mask, 'TD_rate'] = (FFBD_tot.loc[mask, 'TD (Pass)'] / FFBD_tot.loc[mask, 'Att (Pass)']) * 20
FFBD_tot.loc[mask, 'Int_rate'] = 2.375 - (FFBD_tot.loc[mask, 'Int'] / FFBD_tot.loc[mask, 'Att (Pass)']) * 25

Rates = ['Y/A_rate', 'Cmp_rate', 'TD_rate', 'Int_rate']
FFBD_tot[Rates] = FFBD_tot[Rates].clip(lower=0, upper=2.375)
    
FFBD_tot['Passer_Rating'] = (FFBD_tot['Y/A_rate'] + FFBD_tot['Cmp_rate'] + FFBD_tot['TD_rate'] + FFBD_tot['Int_rate'])/6 * 100

FFBD_tot.drop(columns=Rates, inplace=True)

#### Fixing the total TD column to be the sum of TD(Pass), TD(Rush), and TD(Rec)

In [20]:
FFBD_tot['TD'] = FFBD_tot['TD (Pass)'] + FFBD_tot['TD (Rush)'] + FFBD_tot['TD (Rec)']

#### Creating Year Column
##### Here we are using the year text that we added to the player index and creating a new column with the year.

In [22]:
FFBD_tot['Year'] = FFBD_tot.index.str.split('_').str[1]
FFBD_tot.index = FFBD_tot.index.str[:-5]

#### Export to data folder

In [23]:
FFBD_tot.to_csv('../Fantasyfb_Data/FFBD_tot.csv')